### ISSUE TITLE
Databar Expended format

### ISSUE THREAD

**Issue by dylanglockler** [VisionSmarts/pic2shop-pro-barcode-database#3]
Love this app, but I'm trying to work with a databar expanded format and when the app scans, it returns the wrong code, I assume it's recognizing the wrong format. I'm using the demo code:

    p2spro://scan?formats=EAN13,EAN8,UPCE,ITF,CODE39,CODE128,CODABAR&QR&callback=javascript:insertCodeFormat('CODE','FORMAT')

Is there any way to get it to work with databar expanded format?

**Comment by VisionSmarts** [comment]
Here is the full list of symbologies. Only include the ones you need for performance and to avoid misreads (some symbologies don't have much error detection).

EAN13
EAN8
UPCE
EAN_PLUS2
EAN_PLUS5
DATABAR_OMNIDIRECTIONAL
DATABAR_EXPANDED
DATABAR_LIMITED
ITF
CODE39
CODE128
CODABAR
CODE93
STD2OF5
TELEPEN
QR
DATAMATRIX

**Comment by dylanglockler** [comment]
Thanks for that info. I added all three DATABAR symbologies but the scan generates an incorrect value.
Perhaps I'm using the wrong symbology but it seemed to match from my research.
Here's the test barcode:
![Test_Barcode](https://github.com/VisionSmarts/pic2shop-pro-barcode-database/assets/3084083/321721f4-efa2-4ba0-badd-9f4b3072b168)

[https://tracking.clswashing.com/images/Test_Barcode.jpg](url)

**Comment by VisionSmarts** [comment]
It scans as a code128 and the ]c1 at the beginning is the semi standard way
the scanner reports the symbology variant.

**Comment by dylanglockler** [comment]
Perfect, thanks, I'll filter out those three characters and test to see that it works consistently. Appreciate your help!
